---
title: "Finding LS estimates in $R$"
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE, comment=NA, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Read data from an URL

```{r comment=NA, warning=FALSE, message=FALSE}
toluca <- read.table("http://www.cnachtsheim-text.csom.umn.edu/Kutner/Chapter%20%201%20Data%20Sets/CH01TA01.txt", sep ="" , header = FALSE)


#Look at the first 6 entries
head(toluca)
```


### Rename columns

```{r comment=NA, warning=FALSE, message=FALSE}
colnames(toluca) <- c("lotSize", "hours")

#Look at the first 6 entries
head(toluca)
```


### Creating a scatter plot

```{r comment=NA, warning=FALSE, message=FALSE}
library(ggplot2)
ggplot(toluca, aes(x = lotSize, y = hours)) +
  geom_point() +
  labs(x = "Lot Size", y = "Work Hours", title = "Toluca example scatter plot") +
  theme_bw()
```



### Creating a scatter plot, LS line added

```{r comment=NA, warning=FALSE, message=FALSE}
ggplot(toluca, aes(x = lotSize, y = hours)) +
  geom_point() +
  labs(x = "Lot Size", y = "Work Hours", title = "Toluca example, LS line added") +
  geom_smooth(method = "lm", se = FALSE) +
  theme_bw()
```

### Finding the LS estimates
```{r comment=NA, warning=FALSE, message=FALSE}
toluca_LS_model <- lm(hours ~ lotSize, data = toluca)
summary(toluca_LS_model)
```


### Finding fitted values $\hat{y_i}$, and residuals $e_i =(y_i-\hat{y_i})$
```{r comment=NA, warning=FALSE, message=FALSE}
library(moderndive)
Fittedandresiduals <-get_regression_points(toluca_LS_model)
Fittedandresiduals

```

### Calculating $SSE = \sum (y_i-\hat{y_i})^2$

```{r comment=NA, warning=FALSE, message=FALSE}
sum_of_square_of_residuals <- sum(Fittedandresiduals$residual^2)
sum_of_square_of_residuals
```

### Calculating $MSE =SSE/(n-2)$

```{r comment=NA, warning=FALSE, message=FALSE}
Mean_Square_Error <- sum_of_square_of_residuals/(nrow(toluca) -2)
Mean_Square_Error

```

### Calculating Residual Standard Error (estimator of standard deviation $\sigma$) $s = \sqrt(MSE)$

```{r}
s <- sqrt(Mean_Square_Error)
s
```
