---
title:  "Matrix Approach to Simple Linear Regression in $R$"
author: Dr. Hasthika Rupasinghe
date: "August 22th 2023"
output:
  rmdformats::readthedown:
    toc_depth: 3
---


```{r setup, include=FALSE, comment=NA, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Read data from an URL

```{r comment=NA, warning=FALSE, message=FALSE}
toluca <- read.table("http://www.cnachtsheim-text.csom.umn.edu/Kutner/Chapter%20%201%20Data%20Sets/CH01TA01.txt", sep ="" , header = FALSE)


#Look at the first 6 entries
head(toluca)
```


### Rename columns

```{r comment=NA, warning=FALSE, message=FALSE}
colnames(toluca) <- c("lotSize", "hours")

#Look at the first 6 entries
head(toluca)
```

### Making $X$ and $Y$ matrices

```{r comment=NA, warning=FALSE, message=FALSE}
library(Matrix)
n <- nrow(toluca) # Number of observations
n

X <- toluca$lotSize
Y <- toluca$hours

Y <- as.matrix(Y) 
Y                       # This is your vector Y

X <- as.matrix(X)
X                       # Not quite the X matrix we need

X <- cbind(rep(1,n), X) # Adding a column of ones to make the X matrix
X                       # This is your X matrix
```

### Find $X'X$
```{r comment=NA, warning=FALSE, message=FALSE, include=FALSE}

Xt <- t(X) # Taking the transpose of X matrix
Xt

XtX <- Xt %*% X
XtX
```

### Find $X'Y$
```{r comment=NA, warning=FALSE, message=FALSE, include=FALSE}

XtY <- Xt %*% Y
XtY
```

### Find $(X'X)^{-1}$
```{r comment=NA, warning=FALSE, message=FALSE, include=FALSE}

XtXinv <- solve(XtX)
XtXinv
```


### Find $\bf{b} = (X'X)^{-1}X'Y$
```{r comment=NA, warning=FALSE, message=FALSE, include=FALSE}

b <- XtXinv %*% Xt %*% Y
b
```




### Varify answer by Finding the LS estimates uing $lm$ function
```{r comment=NA, warning=FALSE, message=FALSE, include=FALSE}
toluca_LS_model <- lm(hours ~ lotSize, data = toluca)
summary(toluca_LS_model)
```

## Section 5.11: Fitted Values and Residuals 


```{r}

Yhat <- X %*% b # Fitted Values
Yhat

e <- Y - Yhat # Residuals
e

```

## Uses of inverse matrix
Consider the simultanious equations:
$$2y_1+4y_2 =20$$
$$3y_1+y_2=10$$
Using Matrix methods, find the solutions for $y_1$ and $y_2$.

```{r comment=NA, warning=FALSE, message=FALSE}
library(Matrix)
X <- matrix(c(2, 4, 3, 1),ncol=2, nrow = 2, byrow=TRUE)
X
Z<- matrix(c(20,10),ncol =1,nrow=2,byrow=TRUE)
Z
# Find inverse of X matrix 
invX <- solve(X)
invX 

#Multiply invX with Z matrix to find solutions
Y<- invX %*% Z
Y

```

$y_1=2$ and $y_2 =4$















