---
title: "Schedule for STT 4830 - Fall 2024"
author: "Dr. Hasthika Rupasinghe"
date: 'Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")`'
output: 
  bookdown::html_document2: 
    highlight: textmate
    theme: yeti
    toc: true
    css: "CSS/style.css"
---

***


**Week 1: (August 19 -- 23)**

* Go over syllabus.
* [Chapter 1: Linear Regression With One Predictor Variable](PDF_notes/STT4830_Ch_1.pdf)

    * 1.1 Relation between Variables
    * 1.3 Simple Linear Regression Model with Distribution of Error Terms Unspecified
    * 1.4 Data for Regression Analysis
    

***

**Week 2: (August 26 -- August 30)**

* Chapter 1: Linear Regression With One Predictor Variable

    * 1.5 Overview of Steps in Regression Analysis
    * 1.6 Estimation of Regression Function 
    
    
***

**Week 3: (September 2 -- Sep 6)**

* Chapter 1: Linear Regression With One Predictor Variable

    * 1.7 Estimation of Error Terms Variance $\sigma^2$
    * 1.8 Normal Error Regression Model  
    
* Chapter 5: Matrix Approach to Simple Linear Regression Analysis

    * 5.1 Matrices
    * 5.2 Matrix Addition and Subtraction
    * 5.3 Matrix Multiplication 
    
    
* ***Quiz 1***

    
***

**Week 4: (Sep 9  -- Sep 13)**
 
* Chapter 5: Matrix Approach to Simple Linear Regression Analysis

    * 5.4 Special Types of Matrices
    * 5.6 Inverse of a Matrix (In R)
    * 5.9 Simple Linear Regression Model in Matrix Terms
    * 5.10  Least Squares Estimation of Regression Parameters
    
* ***Quiz 2***
    
***

**Week 5: (Sep 16  -- Sep 20)**
 
* Chapter 5: Matrix Approach to Simple Linear Regression Analysis  
    * 5.11  Fitted Values and Residuals
    
* Chapter 3: Diagnostics and Remedial Measures

    * 3.1  Diagnostics for Predictor Variable
    * 3.2  Residuals
    * 3.3  Diagnostics for Residuals
   
* ***Quiz 3***
    
***

**Week 6: (Sep 23  -- Sep 27)**

* Chapter 3: Diagnostics and Remedial Measures
 * 3.3  Diagnostics for Residuals


 * ***Quiz 4***



***

**Week 7: (Sep 30  -- Oct 06)**

* Chapter 3: Diagnostics and Remedial Measures

     * 3.4  Overview of Tests Involving Residuals
     * 3.5  Correlation Test for Nonnality
     * 3.6  Tests for Constancy of Error Variance
     * 3.7  F Test for Lack of Fit
     * 3.8  Overview of Remedial Measures

 *  ***Test 1 ***
 
 
***

**Week 8: (Oct 7  -- Oct 11)**

* Chapter 3: Diagnostics and Remedial Measures
    
     * 3.9  Transformations
     * 3.10  Exploration of Shape of Regression Function
     
 * ***Quiz 5***  
 
***

**Week 9: (Oct 14  -- Oct 18)**

* No Class Tuesday (Fall Break)

* Chapter 6:  Multiple Regression

    * 6.1  Multiple Regression Models
    * 6.2 General Linear Regression Model in Matrix Terms
    * 6.3 Estimation of Regression Coefficients
    * 6.4 Fitted Values and Residuals
    
  * ***Quiz 6*** 
   
***

**Week 10: (Oct 21  -- Oct 25)**

* Chapter 6:  Multiple Regression

    * 6.5 Analysis of Variance Results
    * 6.6 Inferences about Regression Parameters
    * 6.7 Estimation of Mean Response and Prediction of New Observation
    * 6.8 Diagnostics and Remedial Measures
   

* ***Quiz 7*** 

***

    
**Week 11: (Oct 28  -- Nov 01)**

* Chapter 9:  Building the Regression Model I: Model Selection and Validation

    * 9.1 Overview of Model-Building Process 
    * 9.2 Surgical Unit Example
    * 9.3 Criteria for Model Selection 
   
   
* ***Quiz 8*** 


***

**Week 12: (Nov 04  --Nov 08)**

* Chapter 9:  Building the Regression Model I: Model Selection and Validation

     * 9.4 Automatic Search Procedures for Model Selection
     * 9.6 Model Validation
    
     
  *  ***Test 2 ***  
 

***

**Week 13: (Nov 11  --Nov 15)**

  * 14.1 Regression Models with Binary Response Variable
  * 14.2 Sigmoidal Response Functions for Binary Responses

  <!--
  * Watch [9.3 and 9.4 lecture](https://youtu.be/NoR2mXcMxas) and complete the note
  * Watch [9.6 lecture](https://youtu.be/wbCNuuN7i-A) and complete the note
   --> 



  
  <!--
      * Log into the class zoom meeting at 2PM
      * You should get an email with Exam 2 attached at 2.00PM
      * Exam has 6 pages
      * Stay on the zoom meeting and finish the exam in an RMarkdown file (Ends at 3.15PM + 30 min extra if needed)
      * Email me the exam once finished
   --> 

 ***

**Week 14: (Nov 18  --Nov 22)**

**Tuesday:**

<!--

  * Watch [14.1 Regression Models with Binary Response Variable
  and 14.2 Sigmoidal Response Functions for Binary Responses](https://youtu.be/yqdTYICcBF4)
-->

  
  * 14.3 Simple Logistic Regression
  * 14.4 Multiple Logistic Regression
  * 14.5 Inferences about Regression Parameters


*   * ***Quiz 7***

**Thursday:**

* No Class Thursday - state holiday


***

**Week 15: (Nov 25  --Nov 29)**

  * 14.6 Automatic Model Selection Methods
  * 14.7 Tests for Goodness of Fit
  * 14.8 Logistic Regression Diagnostics
  
* ***Quiz 8***

***

**Week 16: (Dec 02  --Dec 03)**

* Dec 03 is Last day of class

***  

  
**Final Exam **

* Tuesday December 10th 08:00 am to 10:30 am

<!--
  * [Data set for question 1](question1.txt)
  * [Data set for question 2](question2.txt)
  * [Data set for question 3](question3.txt)
-->

***