---
title: "Homework for STT 4830 - Fall 2023"
author: "Dr. Hasthika Rupasinghe"
date: 'Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")`'
output: 
  bookdown::html_document2: 
    highlight: textmate
    theme: yeti
    toc: true
    css: "style.css"
---

***

#### ***Homework 1*: Due Tuesday, September 4th**

1) (1.2)
2) (1.5 Give reason for your answer)
3) (1.12)


4) A regression model is $y = \beta_0 + \beta_1x + \epsilon$. There are six observations. The summary statistics are:

$$\sum y_i = 8.5,\quad \sum x_i = 6,\quad \sum x_i^2 = 16,\quad \sum x_iy_i = 15.5,\quad \sum y_i^2 = 17.25$$
Calculate the LS estimate of $\beta_1$

5) You are fitting a linear regression model $y_i = \beta_0 + \beta_1x_i + \epsilon_i$ to 18 observations. You are given the followings:

$$\sum y_i = 252,\quad \sum x_i = 216,\quad \sum x_i^2 = 3092,\quad \sum x_iy_i = 3364,\quad \sum y_i^2 = 4528$$
Calculate the LS estimate of $\beta_1$

6) You are fitting a linear regression model $y_i = \beta_0 + \beta_1x_i + \epsilon_i$ to the following data:


| x | 2 | 5 | 8 | 11| 13| 15| 16| 18|
|--|--|--|--|--|--|--|--|--|--|
| y | -10 | -9 | -4 | 0 | 4 | 5 | 6 | 8|





Calculate the LS estimate of $\beta_1$ using $R$

7) Given the following information 

$$\sum y_i = 1742,\quad \sum x_i = 144,\quad \sum x_i^2 = 2300,\quad \sum x_iy_i = 26696,\quad \sum y_i^2 = 312674 \quad n = 12$$
Determine the LS equation for the model $y_i = \beta_0 + \beta_1x_i + \epsilon_i$.

***


#### ***Homework 2*: Due Tuesday, September 10th**

*Note: In order to receive full credit, please explain your answers well. Simple yes/no answers will not be given credit.*

1) 1.19 (use $R$ as needed)
2) 1.20 (use $R$ as needed)
3) 1.23 (use $R$ as needed)
4) 1.24 (use $R$ as needed)




***


#### ***Homework 3*: Due Tuesday, September 17th**

*You are turning in two files. 1. Hand written work. 2. A printed pdf created by Rmarkdown for the problems where it says "Use R to check your answers".*

1) *5.1*  (Show work by hand calculations. Use R to check your answers)
2) *5.3*  (Hand calculations only)
3) *5.4*  (Show work by hand calculations. Use R to check your answers)
4) *5.6*  (Show work by hand calculations. Use R to check your answers)
5) *5.10* (Hand calculations are encouraged but using R would be easier. I will accept the answer either way)
6) *5.12* (Hand calculations are encouraged but using R would be easier. I will accept the answer either way)
7) *5.14* (Hand calculations are encouraged but using R would be easier. I will accept the answer either way)



***



#### ***Homework 4*: Due Tuesday, September 24th**
Turn in your homework only as a printed *pdf* created in $R$. No handwritten work please!

1) Refer to $\textbf{consumer finance}$ problems 5.5 and 5.13 in the text book.
    a) Using the matrix method, obtain the vector of estimated regression coefficients and vector of residuals. 
    b) Find the hat matrix $\bf{H}$.
    c) Find $s^2(e)$.
 
 
2) Refer to $\textbf{Plastic hardness}$ Problems 1.22 and 5.7. Using matrix methods, obtain the following: 
    (a) $(\bf{X' X})^{-1}$
    (b) $\bf{b}$
    (c) $\bf{\hat{Y}}$
    (d) $\bf{e}$ 
    (e) $\bf{H}$ 

*** 



#### ***Homework 5*: Due Tuesday, October 1st**
Turn in your homework only as a printed *pdf* created in $R$. No handwritten work please!

1) 3.3 - Note: for part e) conduct the Breusch-Pagan test instead Brown-Forsythe test using $\alpha = 0.01$
2) 3.4
3) 3.11
4) 3.15
5) 3.17

***



#### ***Homework 6*: Due Tuesday, October 29th**
Turn in your homework only as a printed *pdf* created in $R$. No handwritten work please!

1) 3.6 a), b), c) Only
2) 3.16


***

<!--

#### ***Homework 7*: Due Tuesday, October 31st**

Turn in your homework only as a *pdf* created in $R$. No handwritten work please!

1) 6.5 (except part f)
2) 6.7
3) 6.8

***

#### ***Homework 8*: Due Tuesday, November 14th**


1) 6.15
2) 6.16
3) 6.17

***



#### ***Homework 9*: Due Tuesday, November 21st (feel free to turn this in after the break)**

Turn in your homework only as a *pdf* created in $R$. No handwritten work please!

1) 9.10
2) 9.11
3) 9.18 (Ignore the second half of part a))
4) 9.22

***
-->


<!--

Old ones

***
#### ***Homework 9*: Due Wednesday, November 16th**

Turn in your homework only as a *pdf* created in $R$. No handwritten work please!

1) 9.22
2) 14.7
3) 14.11

-->

<!--
***

#### ***Homework 8*: Due Thursday, December 6th**

Turn in your homework only as a *pdf* created in $R$. No handwritten work please!

1) 14.7
2) 14.11
3) 14.18
4) 14.20
5) 14.22

***

<!--
#### ***Homework 10*: Due Thursday, November 30th**

Turn in your homework only as a *pdf* created in $R$. No handwritten work please!

5) 14.14
6) 14.20
7) 14.22
Removed 14. 12 and 14.14 from F2022 hw number 8 and combined two of the hw



***
-->



## **Textbook**
[Download PFD textbook here](4830_Textbook.pdf)

***

## **Data sets**
#### [Click here](http://www.cnachtsheim-text.csom.umn.edu/About%20This%20CD.html) to get Data sets to use in the assignments 

***

    
    

    
    