---
title: "Syllabus: STT 4830 - Linear Regression Models"
author: "Syllabus - Fall 2023"
date: ""
output:
  html_document:
    css: "style.css"
    highlight: textmate
    theme: yeti
---

**Instructor:**  Dr. Hashtika Rupasinghe

**Class meeting:** TR 09:30am - 10:45am, WA 209B

**Office:** WA 324

**Office Hours:** In-person: Wednesday 01:00 - 03:00PM, Zoom: Tuesday, Thursday 11:15 - 12:15PM (Click [here](https://appstate.zoom.us/j/92132935945?pwd=SmlZVHk4Wk1MdWlKTDIrdzYzVWhmQT09)) Use the passcode: 642485

<!--Questions related to the class should be addressed with the [piazza account for STT 3851](https://piazza.com/appstate/spring2018/stat3851/home).-->




Prerequisite: MAT 2240 and either STT 3820 or STT 3850.

**Course Description:**  

An introduction to least squares estimation for both simple and multiple regression models. Linear algebra is used to represent both regression models and estimated parameters. Considerable attention is given to the analysis of variance, aptness of the model tests, residual
analysis, the effects of multicollinearity, and variable selection procedures. Logistic regression, Poisson regression, and Generalized Linear Models are also introduced. Theoretical results will be explored with a comprehensive and up to date statistical programming language.


**Course Text:**

Course Text: Applied Linear Statistical Models, Fifth Edition. Michael H. Kutner, Christopher J. Nachtsheim, John Neter ans William Li.

[Download PDF text book here](4830_Textbook.pdf)

**Required Resources:**

Text book, Note book, notes,  pencil, a calculator and access to AppState RStudio server

 **Homework:** Students are expected to work all assigned problems. Only selected assignments or parts of assignments may at times be graded. See schedule for the dates.

**Quizzes:** I anticipate giving in class quizzes weekly during the semester. See schedule for the dates.
<!--The lowest quiz grade will be
dropped when determining the final grade.-->

**Tests:** Two mid exams will be given. 


**Final Exam:** The final exam will be comprehensive, covering all material that is covered in the course. 


**Attendance:** Attendance will be taken  at the end of each class. Students are expected to attend every class. A detailed description of the ASU attendance policy can be found at the following link,
[https://academicaffairs.appstate.edu/resources/syllabi-policy-and-statement-information]

As we are trying to make this experience as close to a regular class as possible, interactivity is important. Therefore you are required to have your video on and actively participate in all the class discussions. — There may be some extra credit allocated for participation and attendance.

**Course Grading:**

* 20% of the grade will come from Homework.
* 25% of the course grade will come from Quizzes.
* 30% of the grade will come from the Mid-Exams.
* 20% of the grade will come from the Final.
* 05% of the grade will come from Attendance.

| Range | Letter Grade | Range | Letter Grade | 
|----------------|---------------------|----------------|---------------------|
|  92.50% and above | A | 72.50-77.49% | C  |
| 90.00--92.49% | A– | 70.00-72.49% | C– |
| 87.50--89.99% | B+ | 67.50-69.99% | D+ |
| 82.50--87.49% | B | 62.50-67.49% | D |
| 80.00-82.49% | B– | 60.00-62.49% | D– |
| 77.50-79.99% | C+ | 59.99% and below | F |


**Academic Integrity Policy, Disability Services, and Religious Holiday Observance:** 

All students must abide by the ASU Academic Integrity Code posted at [www.studentconduct.appstate.edu/](www.studentconduct.appstate.edu/) Those seeking accommodations for a disability should contact the Office of Disability Services (ODS) at [http://www.ods.appstate.edu/](http://www.ods.appstate.edu/) or 828-262-3056.
The statements regarding University policies for students are posted at
[http://academicaffairs.appstate.edu/syllabi](http://academicaffairs.appstate.edu/syllabi)






 



**University Policies**

This course conforms with all Appalachian State University policies with respect to academic integrity, disability services, and class attendance.  The details of the policies may be found at <http://academicaffairs.appstate.edu/resources/syllabi>.



***

#[Home Page](https://lasanthiwatagoda.github.io/STT4830ClassRepo/index.html) 